language: node_js
cache: false
node_js:
  - "8"
  - "10"
  - "12"
os:
  - linux
  - windows
  - osx
install:
  - npm install
script:
  - npm run test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage